FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y openssh-server

RUN mkdir /run/sshd
RUN echo 'root:root' | chpasswd

RUN sed -i 's/#Port 22/Port 24/' /etc/ssh/sshd_config

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN service ssh start

EXPOSE 24

CMD ["/usr/sbin/sshd", "-D"]
