services:
  smtp-server:
    container_name: mail-server
    build:
      context: ./postfix/
      args:
        EMAIL: ${EMAIL}
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
        MAIL_NAME: ${MAIL_NAME}
        SMTP_DOMAIN: ${SMTP_DOMAIN}
        SMTP_PORT: ${SMTP_PORT}
    ports:
      - ${PORT}:25
      - 23:23
    networks:
      subred_proyecto_final:
        ipv4_address: 192.168.1.2

  webserver:
    container_name: apache-server
    build:
      context: ./httpd/
    ports:
      - "8080:80"
      # - 24:24
    volumes:
      - ./httpd/app:/var/www/html
    depends_on:
      - db
    networks:
      subred_proyecto_final:
        ipv4_address: 192.168.1.3

  db:
    container_name: db
    build:
      context: ./db
    # ports:
    #   - 26:26
    volumes:
      - db_data:/var/lib/mysql
    networks:
      subred_proyecto_final:
        ipv4_address: 192.168.1.4

  ssh-client:
    container_name: ssh-client
    build:
      context: ./client
    networks:
      subred_proyecto_final:
        ipv4_address: 192.168.1.6

networks:
  subred_proyecto_final:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  db_data:
# ssh_data:
